package net.azagwen.atbyw.block.registry;

import com.google.common.collect.Maps;
import net.azagwen.atbyw.block.CarvedPumpkinBlockSubClass;
import net.azagwen.atbyw.block.ShatteredGlassBlock;
import net.azagwen.atbyw.block.SurfaceFacingBlock;
import net.azagwen.atbyw.block.extensions.AtbywBlock;
import net.azagwen.atbyw.block.extensions.AtbywPillarBlock;
import net.azagwen.atbyw.block.extensions.AtbywSlabBlock;
import net.azagwen.atbyw.block.extensions.AtbywStairsBlock;
import net.azagwen.atbyw.block.slab.*;
import net.azagwen.atbyw.block.stairs.*;
import net.azagwen.atbyw.util.naming.WoodType;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.*;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.DyeColor;
import net.minecraft.util.StringIdentifiable;

import java.util.Map;

import static net.azagwen.atbyw.block.registry.BlockRegistryUtils.*;
import static net.azagwen.atbyw.main.AtbywMain.BLOCKS_TAB;

public class BuildingBlockRegistry extends AtbywBlocks {
    public static final Map<StringIdentifiable, Block> SHATTERED_GLASS_MAP = Maps.newLinkedHashMap();
    public static final Map<StringIdentifiable, Block> TERRACOTTA_STAIRS_MAP = Maps.newLinkedHashMap();
    public static final Map<StringIdentifiable, Block> TERRACOTTA_SLAB_MAP = Maps.newLinkedHashMap();
    public static final Map<StringIdentifiable, Block> TERRACOTTA_BRICKS_MAP = Maps.newLinkedHashMap();
    public static final Map<StringIdentifiable, Block> TERRACOTTA_BRICKS_STAIRS_MAP = Maps.newLinkedHashMap();
    public static final Map<StringIdentifiable, Block> TERRACOTTA_BRICKS_SLAB_MAP = Maps.newLinkedHashMap();
    public static final Map<StringIdentifiable, Block> CONCRETE_STAIRS_MAP = Maps.newLinkedHashMap();
    public static final Map<StringIdentifiable, Block> CONCRETE_SLAB_MAP = Maps.newLinkedHashMap();
    public static final Map<StringIdentifiable, Block> CINDER_BRICKS_MAP = Maps.newLinkedHashMap();
    public static final Map<StringIdentifiable, Block> CUT_LOG_STAIRS_MAP = Maps.newLinkedHashMap();
    public static final Map<StringIdentifiable, Block> LOG_STAIRS_MAP = Maps.newLinkedHashMap();
    public static final Map<StringIdentifiable, Block> STRIPPED_CUT_LOG_STAIRS_MAP = Maps.newLinkedHashMap();
    public static final Map<StringIdentifiable, Block> STRIPPED_LOG_STAIRS_MAP = Maps.newLinkedHashMap();
    public static final Map<StringIdentifiable, Block> LOG_SLAB_MAP = Maps.newLinkedHashMap();
    public static final Map<StringIdentifiable, Block> STRIPPED_LOG_SLAB_MAP = Maps.newLinkedHashMap();
    public static final Map<StringIdentifiable, Block> BOOKSHELF_MAP = Maps.newLinkedHashMap();

    public static final Block TICKING_DIRT = new Block(FabricBlockSettings.of(Material.SOIL, MapColor.DIRT_BROWN).ticksRandomly().strength(0.5F).sounds(BlockSoundGroup.GRAVEL));
    public static final Block DUMMY_GRASS_BLOCK = new GrassBlock(FabricBlockSettings.of(Material.SOLID_ORGANIC).ticksRandomly().strength(0.6F).sounds(BlockSoundGroup.GRASS));
    public static final Block DUMMY_MYCELIUM = new MyceliumBlock(FabricBlockSettings.of(Material.SOLID_ORGANIC, MapColor.PURPLE).ticksRandomly().strength(0.6F).sounds(BlockSoundGroup.GRASS));

    public static final Block GRANITE_TILES = new Block(FabricBlockSettings.copyOf(Blocks.POLISHED_GRANITE).requiresTool());
    public static final Block DIORITE_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.POLISHED_DIORITE).requiresTool());
    public static final Block ANDESITE_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.POLISHED_ANDESITE).requiresTool());
    public static final Block GRANITE_TILES_STAIRS = new AtbywStairsBlock(Blocks.POLISHED_GRANITE, FabricBlockSettings.copyOf(Blocks.POLISHED_GRANITE).requiresTool());
    public static final Block DIORITE_BRICKS_STAIRS = new AtbywStairsBlock(Blocks.POLISHED_DIORITE, FabricBlockSettings.copyOf(Blocks.POLISHED_DIORITE).requiresTool());
    public static final Block ANDESITE_BRICKS_STAIRS = new AtbywStairsBlock(Blocks.POLISHED_ANDESITE, FabricBlockSettings.copyOf(Blocks.POLISHED_ANDESITE).requiresTool());
    public static final Block GRANITE_TILES_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.POLISHED_GRANITE).requiresTool());
    public static final Block DIORITE_BRICKS_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.POLISHED_DIORITE).requiresTool());
    public static final Block ANDESITE_BRICKS_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.POLISHED_ANDESITE).requiresTool());
    public static final Block RAW_CACTUS_PLANKS = new Block(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS));
    public static final Block CACTUS_PLANKS = new Block(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS));
    public static final Block CACTUS_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB));
    public static final Block CACTUS_STAIRS = new AtbywStairsBlock(CACTUS_PLANKS, FabricBlockSettings.copyOf(Blocks.OAK_STAIRS));
    public static final Block GRASS_BLOCK_STAIRS = new SpreadableStairsBlock(DUMMY_GRASS_BLOCK, Blocks.GRASS_BLOCK, FabricBlockSettings.copyOf(DUMMY_GRASS_BLOCK));
    public static final Block DIRT_STAIRS = new DirtStairsBlock(TICKING_DIRT, FabricBlockSettings.copyOf(TICKING_DIRT));
    public static final Block COARSE_DIRT_STAIRS = new AtbywStairsBlock(Blocks.COARSE_DIRT, FabricBlockSettings.of(Material.SOIL, MapColor.DIRT_BROWN).strength(0.5F).sounds(BlockSoundGroup.GRAVEL).ticksRandomly());
    public static final Block PODZOL_STAIRS = new AtbywStairsBlock(Blocks.PODZOL, FabricBlockSettings.of(Material.SOIL, MapColor.SPRUCE_BROWN).strength(0.5F).sounds(BlockSoundGroup.GRAVEL));
    public static final Block ROOTED_DIRT_STAIRS = new AtbywStairsBlock(Blocks.ROOTED_DIRT, FabricBlockSettings.copyOf(Blocks.ROOTED_DIRT));
    public static final Block MYCELIUM_STAIRS = new SpreadableStairsBlock(DUMMY_MYCELIUM, Blocks.MYCELIUM, FabricBlockSettings.copyOf(DUMMY_MYCELIUM));
    public static final Block GRASS_PATH_STAIRS = new GrassPathStairsBlock(Blocks.DIRT_PATH, FabricBlockSettings.copyOf(Blocks.DIRT_PATH));
    public static final Block CRIMSON_NYLIUM_STAIRS = new NyliumStairsBlock(Blocks.CRIMSON_NYLIUM, FabricBlockSettings.copyOf(Blocks.CRIMSON_NYLIUM).requiresTool());
    public static final Block WARPED_NYLIUM_STAIRS = new NyliumStairsBlock(Blocks.WARPED_NYLIUM, FabricBlockSettings.copyOf(Blocks.WARPED_NYLIUM).requiresTool());
    public static final Block NETHERRACK_STAIRS = new NetherrackStairsBlock(Blocks.NETHERRACK, FabricBlockSettings.copyOf(Blocks.NETHERRACK).requiresTool());
    public static final Block GRASS_BLOCK_SLAB = new SpreadableSlabBlock(Blocks.GRASS_BLOCK, FabricBlockSettings.copyOf(DUMMY_GRASS_BLOCK));
    public static final Block DIRT_SLAB = new DirtSlabBlock(FabricBlockSettings.copyOf(TICKING_DIRT));
    public static final Block COARSE_DIRT_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.COARSE_DIRT));
    public static final Block PODZOL_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.PODZOL));
    public static final Block ROOTED_DIRT_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.ROOTED_DIRT));
    public static final Block MYCELIUM_SLAB = new SpreadableSlabBlock(Blocks.MYCELIUM, FabricBlockSettings.copyOf(DUMMY_MYCELIUM));
    public static final Block GRASS_PATH_SLAB = new GrassPathSlabBlock(FabricBlockSettings.copyOf(Blocks.DIRT_PATH));
    public static final Block CRIMSON_NYLIUM_SLAB = new NyliumSlabBlock(FabricBlockSettings.copyOf(Blocks.CRIMSON_NYLIUM).requiresTool());
    public static final Block WARPED_NYLIUM_SLAB = new NyliumSlabBlock(FabricBlockSettings.copyOf(Blocks.WARPED_NYLIUM).requiresTool());
    public static final Block NETHERRACK_SLAB = new NetherrackSlabBlock(FabricBlockSettings.copyOf(Blocks.NETHERRACK).requiresTool());
    public static final Block SAND_SLAB = new FallingSlabBlock(14406560, FabricBlockSettings.copyOf(Blocks.SAND));
    public static final Block RED_SAND_SLAB = new FallingSlabBlock(11098145, FabricBlockSettings.copyOf(Blocks.RED_SAND));
    public static final Block GRAVEL_SLAB = new FallingSlabBlock(-8356741, FabricBlockSettings.copyOf(Blocks.GRAVEL));
    public static final Block SAND_STAIRS = new FallingStairsBlock(14406560, Blocks.SAND, SAND_SLAB, FabricBlockSettings.copyOf(Blocks.SAND));
    public static final Block RED_SAND_STAIRS = new FallingStairsBlock(11098145, Blocks.RED_SAND, RED_SAND_SLAB, FabricBlockSettings.copyOf(Blocks.RED_SAND));
    public static final Block GRAVEL_STAIRS = new FallingStairsBlock(-8356741, Blocks.GRAVEL, GRAVEL_SLAB, FabricBlockSettings.copyOf(Blocks.GRAVEL));
    public static final Block CUT_OAK_LOG_STAIRS = new PillarStairsBlock(CUT_LOG_STAIRS_MAP, WoodType.OAK, Blocks.OAK_LOG, logSettings(Blocks.OAK_LOG));
    public static final Block CUT_SPRUCE_LOG_STAIRS = new PillarStairsBlock(CUT_LOG_STAIRS_MAP, WoodType.SPRUCE, Blocks.SPRUCE_LOG, logSettings(Blocks.SPRUCE_LOG));
    public static final Block CUT_BIRCH_LOG_STAIRS = new PillarStairsBlock(CUT_LOG_STAIRS_MAP, WoodType.BIRCH, Blocks.BIRCH_LOG, logSettings(Blocks.BIRCH_LOG));
    public static final Block CUT_JUNGLE_LOG_STAIRS = new PillarStairsBlock(CUT_LOG_STAIRS_MAP, WoodType.JUNGLE, Blocks.JUNGLE_LOG, logSettings(Blocks.JUNGLE_LOG));
    public static final Block CUT_ACACIA_LOG_STAIRS = new PillarStairsBlock(CUT_LOG_STAIRS_MAP, WoodType.ACACIA, Blocks.ACACIA_LOG, logSettings(Blocks.ACACIA_LOG));
    public static final Block CUT_DARK_OAK_LOG_STAIRS = new PillarStairsBlock(CUT_LOG_STAIRS_MAP, WoodType.DARK_OAK, Blocks.DARK_OAK_LOG, logSettings(Blocks.DARK_OAK_LOG));
    public static final Block CUT_CRIMSON_STEM_STAIRS = new PillarStairsBlock(CUT_LOG_STAIRS_MAP, WoodType.CRIMSON, Blocks.CRIMSON_STEM, logSettings(Blocks.CRIMSON_STEM));
    public static final Block CUT_WARPED_STEM_STAIRS = new PillarStairsBlock(CUT_LOG_STAIRS_MAP, WoodType.WARPED, Blocks.WARPED_STEM, logSettings(Blocks.WARPED_STEM));
    public static final Block OAK_LOG_STAIRS = new PillarStairsBlock(LOG_STAIRS_MAP, WoodType.OAK, Blocks.OAK_LOG, logSettings(Blocks.OAK_LOG));
    public static final Block SPRUCE_LOG_STAIRS = new PillarStairsBlock(LOG_STAIRS_MAP, WoodType.SPRUCE, Blocks.SPRUCE_LOG, logSettings(Blocks.SPRUCE_LOG));
    public static final Block BIRCH_LOG_STAIRS = new PillarStairsBlock(LOG_STAIRS_MAP, WoodType.BIRCH, Blocks.BIRCH_LOG, logSettings(Blocks.BIRCH_LOG));
    public static final Block JUNGLE_LOG_STAIRS = new PillarStairsBlock(LOG_STAIRS_MAP, WoodType.JUNGLE, Blocks.JUNGLE_LOG, logSettings(Blocks.JUNGLE_LOG));
    public static final Block ACACIA_LOG_STAIRS = new PillarStairsBlock(LOG_STAIRS_MAP, WoodType.ACACIA, Blocks.ACACIA_LOG, logSettings(Blocks.ACACIA_LOG));
    public static final Block DARK_OAK_LOG_STAIRS = new PillarStairsBlock(LOG_STAIRS_MAP, WoodType.DARK_OAK, Blocks.DARK_OAK_LOG, logSettings(Blocks.DARK_OAK_LOG));
    public static final Block CRIMSON_STEM_STAIRS = new PillarStairsBlock(LOG_STAIRS_MAP, WoodType.CRIMSON, Blocks.CRIMSON_STEM, logSettings(Blocks.CRIMSON_STEM));
    public static final Block WARPED_STEM_STAIRS = new PillarStairsBlock(LOG_STAIRS_MAP, WoodType.WARPED, Blocks.WARPED_STEM, logSettings(Blocks.WARPED_STEM));
    public static final Block STRIPPED_CUT_OAK_LOG_STAIRS = new PillarStairsBlock(STRIPPED_CUT_LOG_STAIRS_MAP, WoodType.OAK, Blocks.STRIPPED_OAK_LOG, logSettings(Blocks.STRIPPED_OAK_LOG));
    public static final Block STRIPPED_CUT_SPRUCE_LOG_STAIRS = new PillarStairsBlock(STRIPPED_CUT_LOG_STAIRS_MAP, WoodType.SPRUCE, Blocks.STRIPPED_SPRUCE_LOG, logSettings(Blocks.STRIPPED_SPRUCE_LOG));
    public static final Block STRIPPED_CUT_BIRCH_LOG_STAIRS = new PillarStairsBlock(STRIPPED_CUT_LOG_STAIRS_MAP, WoodType.BIRCH, Blocks.STRIPPED_BIRCH_LOG, logSettings(Blocks.STRIPPED_BIRCH_LOG));
    public static final Block STRIPPED_CUT_JUNGLE_LOG_STAIRS = new PillarStairsBlock(STRIPPED_CUT_LOG_STAIRS_MAP, WoodType.JUNGLE, Blocks.STRIPPED_JUNGLE_LOG, logSettings(Blocks.STRIPPED_JUNGLE_LOG));
    public static final Block STRIPPED_CUT_ACACIA_LOG_STAIRS = new PillarStairsBlock(STRIPPED_CUT_LOG_STAIRS_MAP, WoodType.ACACIA, Blocks.STRIPPED_ACACIA_LOG, logSettings(Blocks.STRIPPED_ACACIA_LOG));
    public static final Block STRIPPED_CUT_DARK_OAK_LOG_STAIRS = new PillarStairsBlock(STRIPPED_CUT_LOG_STAIRS_MAP, WoodType.DARK_OAK, Blocks.STRIPPED_DARK_OAK_LOG, logSettings(Blocks.STRIPPED_DARK_OAK_LOG));
    public static final Block STRIPPED_CUT_CRIMSON_STEM_STAIRS = new PillarStairsBlock(STRIPPED_CUT_LOG_STAIRS_MAP, WoodType.CRIMSON, Blocks.STRIPPED_CRIMSON_STEM, logSettings(Blocks.STRIPPED_CRIMSON_STEM));
    public static final Block STRIPPED_CUT_WARPED_STEM_STAIRS = new PillarStairsBlock(STRIPPED_CUT_LOG_STAIRS_MAP, WoodType.WARPED, Blocks.STRIPPED_WARPED_STEM, logSettings(Blocks.STRIPPED_WARPED_STEM));
    public static final Block STRIPPED_OAK_LOG_STAIRS = new PillarStairsBlock(STRIPPED_LOG_STAIRS_MAP, WoodType.OAK, Blocks.STRIPPED_OAK_LOG, logSettings(Blocks.STRIPPED_OAK_LOG));
    public static final Block STRIPPED_SPRUCE_LOG_STAIRS = new PillarStairsBlock(STRIPPED_LOG_STAIRS_MAP, WoodType.SPRUCE, Blocks.STRIPPED_SPRUCE_LOG, logSettings(Blocks.STRIPPED_SPRUCE_LOG));
    public static final Block STRIPPED_BIRCH_LOG_STAIRS = new PillarStairsBlock(STRIPPED_LOG_STAIRS_MAP, WoodType.BIRCH, Blocks.STRIPPED_BIRCH_LOG, logSettings(Blocks.STRIPPED_BIRCH_LOG));
    public static final Block STRIPPED_JUNGLE_LOG_STAIRS = new PillarStairsBlock(STRIPPED_LOG_STAIRS_MAP, WoodType.JUNGLE, Blocks.STRIPPED_JUNGLE_LOG, logSettings(Blocks.STRIPPED_JUNGLE_LOG));
    public static final Block STRIPPED_ACACIA_LOG_STAIRS = new PillarStairsBlock(STRIPPED_LOG_STAIRS_MAP, WoodType.ACACIA, Blocks.STRIPPED_ACACIA_LOG, logSettings(Blocks.STRIPPED_ACACIA_LOG));
    public static final Block STRIPPED_DARK_OAK_LOG_STAIRS = new PillarStairsBlock(STRIPPED_LOG_STAIRS_MAP, WoodType.DARK_OAK, Blocks.STRIPPED_DARK_OAK_LOG, logSettings(Blocks.STRIPPED_DARK_OAK_LOG));
    public static final Block STRIPPED_CRIMSON_STEM_STAIRS = new PillarStairsBlock(STRIPPED_LOG_STAIRS_MAP, WoodType.CRIMSON, Blocks.STRIPPED_CRIMSON_STEM, logSettings(Blocks.STRIPPED_CRIMSON_STEM));
    public static final Block STRIPPED_WARPED_STEM_STAIRS = new PillarStairsBlock(STRIPPED_LOG_STAIRS_MAP, WoodType.WARPED, Blocks.STRIPPED_WARPED_STEM, logSettings(Blocks.STRIPPED_WARPED_STEM));
    public static final Block OAK_LOG_SLAB = new PillarSlabBlock(LOG_SLAB_MAP, WoodType.OAK, logSettings(Blocks.OAK_LOG));
    public static final Block SPRUCE_LOG_SLAB = new PillarSlabBlock(LOG_SLAB_MAP, WoodType.SPRUCE, logSettings(Blocks.SPRUCE_LOG));
    public static final Block BIRCH_LOG_SLAB = new PillarSlabBlock(LOG_SLAB_MAP, WoodType.BIRCH, logSettings(Blocks.BIRCH_LOG));
    public static final Block JUNGLE_LOG_SLAB = new PillarSlabBlock(LOG_SLAB_MAP, WoodType.JUNGLE, logSettings(Blocks.JUNGLE_LOG));
    public static final Block ACACIA_LOG_SLAB = new PillarSlabBlock(LOG_SLAB_MAP, WoodType.ACACIA, logSettings(Blocks.ACACIA_LOG));
    public static final Block DARK_OAK_LOG_SLAB = new PillarSlabBlock(LOG_SLAB_MAP, WoodType.DARK_OAK, logSettings(Blocks.DARK_OAK_LOG));
    public static final Block CRIMSON_STEM_SLAB = new PillarSlabBlock(LOG_SLAB_MAP, WoodType.CRIMSON, logSettings(Blocks.CRIMSON_STEM));
    public static final Block WARPED_STEM_SLAB = new PillarSlabBlock(LOG_SLAB_MAP, WoodType.WARPED, logSettings(Blocks.WARPED_STEM));
    public static final Block STRIPPED_OAK_LOG_SLAB = new PillarSlabBlock(STRIPPED_LOG_SLAB_MAP, WoodType.OAK, logSettings(Blocks.STRIPPED_OAK_LOG));
    public static final Block STRIPPED_SPRUCE_LOG_SLAB = new PillarSlabBlock(STRIPPED_LOG_SLAB_MAP, WoodType.SPRUCE, logSettings(Blocks.STRIPPED_SPRUCE_LOG));
    public static final Block STRIPPED_BIRCH_LOG_SLAB = new PillarSlabBlock(STRIPPED_LOG_SLAB_MAP, WoodType.BIRCH, logSettings(Blocks.STRIPPED_BIRCH_LOG));
    public static final Block STRIPPED_JUNGLE_LOG_SLAB = new PillarSlabBlock(STRIPPED_LOG_SLAB_MAP, WoodType.JUNGLE, logSettings(Blocks.STRIPPED_JUNGLE_LOG));
    public static final Block STRIPPED_ACACIA_LOG_SLAB = new PillarSlabBlock(STRIPPED_LOG_SLAB_MAP, WoodType.ACACIA, logSettings(Blocks.STRIPPED_ACACIA_LOG));
    public static final Block STRIPPED_DARK_OAK_LOG_SLAB = new PillarSlabBlock(STRIPPED_LOG_SLAB_MAP, WoodType.DARK_OAK, logSettings(Blocks.STRIPPED_DARK_OAK_LOG));
    public static final Block STRIPPED_CRIMSON_STEM_SLAB = new PillarSlabBlock(STRIPPED_LOG_SLAB_MAP, WoodType.CRIMSON, logSettings(Blocks.STRIPPED_CRIMSON_STEM));
    public static final Block STRIPPED_WARPED_STEM_SLAB = new PillarSlabBlock(STRIPPED_LOG_SLAB_MAP, WoodType.WARPED, logSettings(Blocks.STRIPPED_WARPED_STEM));
    public static final Block SHATTERED_GLASS = createShatteredGlass(Blocks.GLASS);
    public static final Block SOUL_JACK_O_LANTERN = new CarvedPumpkinBlockSubClass(FabricBlockSettings.of(Material.GOURD, MapColor.ORANGE).strength(1.0F).sounds(BlockSoundGroup.WOOD).luminance((state) -> 10).allowsSpawning(AtbywBlocks::always));
    public static final Block SPRUCE_BOOKSHELF = new AtbywBlock(BOOKSHELF_MAP, WoodType.SPRUCE, FabricBlockSettings.copyOf(Blocks.BOOKSHELF));
    public static final Block BIRCH_BOOKSHELF = new AtbywBlock(BOOKSHELF_MAP, WoodType.BIRCH, FabricBlockSettings.copyOf(Blocks.BOOKSHELF));
    public static final Block JUNGLE_BOOKSHELF = new AtbywBlock(BOOKSHELF_MAP, WoodType.JUNGLE, FabricBlockSettings.copyOf(Blocks.BOOKSHELF));
    public static final Block ACACIA_BOOKSHELF = new AtbywBlock(BOOKSHELF_MAP, WoodType.ACACIA, FabricBlockSettings.copyOf(Blocks.BOOKSHELF));
    public static final Block DARK_OAK_BOOKSHELF = new AtbywBlock(BOOKSHELF_MAP, WoodType.DARK_OAK, FabricBlockSettings.copyOf(Blocks.BOOKSHELF));
    public static final Block CRIMSON_BOOKSHELF = new AtbywBlock(BOOKSHELF_MAP, WoodType.CRIMSON, FabricBlockSettings.copyOf(Blocks.BOOKSHELF));
    public static final Block WARPED_BOOKSHELF = new AtbywBlock(BOOKSHELF_MAP, WoodType.WARPED, FabricBlockSettings.copyOf(Blocks.BOOKSHELF));
    public static final Block PURPUR_TILES = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK).requiresTool());
    public static final Block CHISELED_PURPUR_BLOCK = new SurfaceFacingBlock(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK).requiresTool());
    public static final Block CUT_PURPUR_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK).requiresTool());
    public static final Block SMOOTH_PURPUR_BLOCK = new Block(FabricBlockSettings.copyOf(Blocks.PURPUR_BLOCK).requiresTool());
    public static final Block PURPUR_TILES_STAIRS = new AtbywStairsBlock(PURPUR_TILES, FabricBlockSettings.copyOf(Blocks.PURPUR_STAIRS).requiresTool());
    public static final Block CUT_PURPUR_STAIRS = new AtbywStairsBlock(CUT_PURPUR_BLOCK, FabricBlockSettings.copyOf(Blocks.PURPUR_STAIRS).requiresTool());
    public static final Block SMOOTH_PURPUR_STAIRS = new AtbywStairsBlock(CUT_PURPUR_BLOCK, FabricBlockSettings.copyOf(Blocks.PURPUR_STAIRS).requiresTool());
    public static final Block PURPUR_TILES_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.PURPUR_SLAB).requiresTool());
    public static final Block CUT_PURPUR_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.PURPUR_SLAB).requiresTool());
    public static final Block SMOOTH_PURPUR_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.PURPUR_SLAB).requiresTool());
    public static final Block COMPACTED_SNOW_BLOCK = new Block(FabricBlockSettings.of(Material.SNOW_BLOCK).strength(0.4F).requiresTool().sounds(BlockSoundGroup.SNOW));
    public static final Block COMPACTED_SNOW_BRICKS = new Block(FabricBlockSettings.copyOf(COMPACTED_SNOW_BLOCK));
    public static final Block CHISELED_COMPACTED_SNOW_BRICKS = new Block(FabricBlockSettings.copyOf(COMPACTED_SNOW_BLOCK));
    public static final Block PACKED_ICE_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.PACKED_ICE));
    public static final Block CHISELED_PACKED_ICE_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.PACKED_ICE));
    public static final Block BLUE_ICE_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BLUE_ICE));
    public static final Block CHISELED_BLUE_ICE_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.BLUE_ICE));
    public static final Block COMPACTED_SNOW_BLOCK_STAIRS = new AtbywStairsBlock(COMPACTED_SNOW_BLOCK, FabricBlockSettings.copyOf(COMPACTED_SNOW_BLOCK));
    public static final Block COMPACTED_SNOW_BRICKS_STAIRS = new AtbywStairsBlock(COMPACTED_SNOW_BRICKS, FabricBlockSettings.copyOf(COMPACTED_SNOW_BLOCK));
    public static final Block PACKED_ICE_STAIRS = new AtbywStairsBlock(Blocks.PACKED_ICE, FabricBlockSettings.copyOf(Blocks.PACKED_ICE));
    public static final Block BLUE_ICE_STAIRS = new AtbywStairsBlock(Blocks.BLUE_ICE, FabricBlockSettings.copyOf(Blocks.BLUE_ICE));
    public static final Block PACKED_ICE_BRICKS_STAIRS = new AtbywStairsBlock(Blocks.PACKED_ICE, FabricBlockSettings.copyOf(Blocks.PACKED_ICE));
    public static final Block BLUE_ICE_BRICKS_STAIRS = new AtbywStairsBlock(Blocks.BLUE_ICE, FabricBlockSettings.copyOf(Blocks.BLUE_ICE));
    public static final Block COMPACTED_SNOW_BLOCK_SLAB = new SlabBlock(FabricBlockSettings.copyOf(COMPACTED_SNOW_BLOCK));
    public static final Block COMPACTED_SNOW_BRICKS_SLAB = new SlabBlock(FabricBlockSettings.copyOf(COMPACTED_SNOW_BLOCK));
    public static final Block PACKED_ICE_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.PACKED_ICE));
    public static final Block BLUE_ICE_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.BLUE_ICE));
    public static final Block PACKED_ICE_BRICKS_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.PACKED_ICE));
    public static final Block BLUE_ICE_BRICKS_SLAB = new SlabBlock(FabricBlockSettings.copyOf(Blocks.BLUE_ICE));
    public static final Block WHITE_STAINED_SHATTERED_GLASS = createShatteredGlass(Blocks.WHITE_STAINED_GLASS);
    public static final Block ORANGE_STAINED_SHATTERED_GLASS = createShatteredGlass(Blocks.ORANGE_STAINED_GLASS);
    public static final Block MAGENTA_STAINED_SHATTERED_GLASS = createShatteredGlass(Blocks.MAGENTA_STAINED_GLASS);
    public static final Block LIGHT_BLUE_STAINED_SHATTERED_GLASS = createShatteredGlass(Blocks.LIGHT_BLUE_STAINED_GLASS);
    public static final Block YELLOW_STAINED_SHATTERED_GLASS = createShatteredGlass(Blocks.YELLOW_STAINED_GLASS);
    public static final Block LIME_STAINED_SHATTERED_GLASS = createShatteredGlass(Blocks.LIME_STAINED_GLASS);
    public static final Block PINK_STAINED_SHATTERED_GLASS = createShatteredGlass(Blocks.PINK_STAINED_GLASS);
    public static final Block GRAY_STAINED_SHATTERED_GLASS = createShatteredGlass(Blocks.GRAY_STAINED_GLASS);
    public static final Block LIGHT_GRAY_STAINED_SHATTERED_GLASS = createShatteredGlass(Blocks.LIGHT_GRAY_STAINED_GLASS);
    public static final Block CYAN_STAINED_SHATTERED_GLASS = createShatteredGlass(Blocks.CYAN_STAINED_GLASS);
    public static final Block PURPLE_STAINED_SHATTERED_GLASS = createShatteredGlass(Blocks.PURPLE_STAINED_GLASS);
    public static final Block BLUE_STAINED_SHATTERED_GLASS = createShatteredGlass(Blocks.BLUE_STAINED_GLASS);
    public static final Block BROWN_STAINED_SHATTERED_GLASS = createShatteredGlass(Blocks.BROWN_STAINED_GLASS);
    public static final Block GREEN_STAINED_SHATTERED_GLASS = createShatteredGlass(Blocks.GREEN_STAINED_GLASS);
    public static final Block RED_STAINED_SHATTERED_GLASS = createShatteredGlass(Blocks.RED_STAINED_GLASS);
    public static final Block BLACK_STAINED_SHATTERED_GLASS = createShatteredGlass(Blocks.BLACK_STAINED_GLASS);
    public static final Block BASALT_BRICKS = new Block(basaltSettings());
    public static final Block BASALT_PILLAR = new PillarBlock(basaltSettings());
    public static final Block TERRACOTTA_STAIRS = new AtbywStairsBlock(Blocks.TERRACOTTA, FabricBlockSettings.copyOf(Blocks.TERRACOTTA).requiresTool());
    public static final Block WHITE_TERRACOTTA_STAIRS = new AtbywStairsBlock(TERRACOTTA_STAIRS_MAP, DyeColor.WHITE, Blocks.WHITE_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).requiresTool());
    public static final Block ORANGE_TERRACOTTA_STAIRS = new AtbywStairsBlock(TERRACOTTA_STAIRS_MAP, DyeColor.ORANGE, Blocks.ORANGE_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.ORANGE_TERRACOTTA).requiresTool());
    public static final Block MAGENTA_TERRACOTTA_STAIRS = new AtbywStairsBlock(TERRACOTTA_STAIRS_MAP, DyeColor.MAGENTA, Blocks.MAGENTA_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.MAGENTA_TERRACOTTA).requiresTool());
    public static final Block LIGHT_BLUE_TERRACOTTA_STAIRS = new AtbywStairsBlock(TERRACOTTA_STAIRS_MAP, DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.LIGHT_BLUE_TERRACOTTA).requiresTool());
    public static final Block YELLOW_TERRACOTTA_STAIRS = new AtbywStairsBlock(TERRACOTTA_STAIRS_MAP, DyeColor.YELLOW, Blocks.YELLOW_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.YELLOW_TERRACOTTA).requiresTool());
    public static final Block LIME_TERRACOTTA_STAIRS = new AtbywStairsBlock(TERRACOTTA_STAIRS_MAP, DyeColor.LIME, Blocks.LIME_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.LIME_TERRACOTTA).requiresTool());
    public static final Block PINK_TERRACOTTA_STAIRS = new AtbywStairsBlock(TERRACOTTA_STAIRS_MAP, DyeColor.PINK, Blocks.PINK_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.PINK_TERRACOTTA).requiresTool());
    public static final Block GRAY_TERRACOTTA_STAIRS = new AtbywStairsBlock(TERRACOTTA_STAIRS_MAP, DyeColor.GRAY, Blocks.GRAY_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.GRAY_TERRACOTTA).requiresTool());
    public static final Block LIGHT_GRAY_TERRACOTTA_STAIRS = new AtbywStairsBlock(TERRACOTTA_STAIRS_MAP, DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.LIGHT_GRAY_TERRACOTTA).requiresTool());
    public static final Block CYAN_TERRACOTTA_STAIRS = new AtbywStairsBlock(TERRACOTTA_STAIRS_MAP, DyeColor.CYAN, Blocks.CYAN_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.CYAN_TERRACOTTA).requiresTool());
    public static final Block PURPLE_TERRACOTTA_STAIRS = new AtbywStairsBlock(TERRACOTTA_STAIRS_MAP, DyeColor.PURPLE, Blocks.PURPLE_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.PURPLE_TERRACOTTA).requiresTool());
    public static final Block BLUE_TERRACOTTA_STAIRS = new AtbywStairsBlock(TERRACOTTA_STAIRS_MAP, DyeColor.BLUE, Blocks.BLUE_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.BLUE_TERRACOTTA).requiresTool());
    public static final Block BROWN_TERRACOTTA_STAIRS = new AtbywStairsBlock(TERRACOTTA_STAIRS_MAP, DyeColor.BROWN, Blocks.BROWN_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.BROWN_TERRACOTTA).requiresTool());
    public static final Block GREEN_TERRACOTTA_STAIRS = new AtbywStairsBlock(TERRACOTTA_STAIRS_MAP, DyeColor.GREEN, Blocks.GREEN_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.GREEN_TERRACOTTA).requiresTool());
    public static final Block RED_TERRACOTTA_STAIRS = new AtbywStairsBlock(TERRACOTTA_STAIRS_MAP, DyeColor.RED, Blocks.RED_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.RED_TERRACOTTA).requiresTool());
    public static final Block BLACK_TERRACOTTA_STAIRS = new AtbywStairsBlock(TERRACOTTA_STAIRS_MAP, DyeColor.BLACK, Blocks.BLACK_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.BLACK_TERRACOTTA).requiresTool());
    public static final Block TERRACOTTA_SLAB = new AtbywSlabBlock(FabricBlockSettings.copyOf(Blocks.TERRACOTTA).requiresTool());
    public static final Block WHITE_TERRACOTTA_SLAB = new AtbywSlabBlock(TERRACOTTA_SLAB_MAP, DyeColor.WHITE, FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).requiresTool());
    public static final Block ORANGE_TERRACOTTA_SLAB = new AtbywSlabBlock(TERRACOTTA_SLAB_MAP, DyeColor.ORANGE, FabricBlockSettings.copyOf(Blocks.ORANGE_TERRACOTTA).requiresTool());
    public static final Block MAGENTA_TERRACOTTA_SLAB = new AtbywSlabBlock(TERRACOTTA_SLAB_MAP, DyeColor.MAGENTA, FabricBlockSettings.copyOf(Blocks.MAGENTA_TERRACOTTA).requiresTool());
    public static final Block LIGHT_BLUE_TERRACOTTA_SLAB = new AtbywSlabBlock(TERRACOTTA_SLAB_MAP, DyeColor.LIGHT_BLUE, FabricBlockSettings.copyOf(Blocks.LIGHT_BLUE_TERRACOTTA).requiresTool());
    public static final Block YELLOW_TERRACOTTA_SLAB = new AtbywSlabBlock(TERRACOTTA_SLAB_MAP, DyeColor.YELLOW, FabricBlockSettings.copyOf(Blocks.YELLOW_TERRACOTTA).requiresTool());
    public static final Block LIME_TERRACOTTA_SLAB = new AtbywSlabBlock(TERRACOTTA_SLAB_MAP, DyeColor.LIME, FabricBlockSettings.copyOf(Blocks.LIME_TERRACOTTA).requiresTool());
    public static final Block PINK_TERRACOTTA_SLAB = new AtbywSlabBlock(TERRACOTTA_SLAB_MAP, DyeColor.PINK, FabricBlockSettings.copyOf(Blocks.PINK_TERRACOTTA).requiresTool());
    public static final Block GRAY_TERRACOTTA_SLAB = new AtbywSlabBlock(TERRACOTTA_SLAB_MAP, DyeColor.GRAY, FabricBlockSettings.copyOf(Blocks.GRAY_TERRACOTTA).requiresTool());
    public static final Block LIGHT_GRAY_TERRACOTTA_SLAB = new AtbywSlabBlock(TERRACOTTA_SLAB_MAP, DyeColor.LIGHT_GRAY, FabricBlockSettings.copyOf(Blocks.LIGHT_GRAY_TERRACOTTA).requiresTool());
    public static final Block CYAN_TERRACOTTA_SLAB = new AtbywSlabBlock(TERRACOTTA_SLAB_MAP, DyeColor.CYAN, FabricBlockSettings.copyOf(Blocks.CYAN_TERRACOTTA).requiresTool());
    public static final Block PURPLE_TERRACOTTA_SLAB = new AtbywSlabBlock(TERRACOTTA_SLAB_MAP, DyeColor.PURPLE, FabricBlockSettings.copyOf(Blocks.PURPLE_TERRACOTTA).requiresTool());
    public static final Block BLUE_TERRACOTTA_SLAB = new AtbywSlabBlock(TERRACOTTA_SLAB_MAP, DyeColor.BLUE, FabricBlockSettings.copyOf(Blocks.BLUE_TERRACOTTA).requiresTool());
    public static final Block BROWN_TERRACOTTA_SLAB = new AtbywSlabBlock(TERRACOTTA_SLAB_MAP, DyeColor.BROWN, FabricBlockSettings.copyOf(Blocks.BROWN_TERRACOTTA).requiresTool());
    public static final Block GREEN_TERRACOTTA_SLAB = new AtbywSlabBlock(TERRACOTTA_SLAB_MAP, DyeColor.GREEN, FabricBlockSettings.copyOf(Blocks.GREEN_TERRACOTTA).requiresTool());
    public static final Block RED_TERRACOTTA_SLAB = new AtbywSlabBlock(TERRACOTTA_SLAB_MAP, DyeColor.RED, FabricBlockSettings.copyOf(Blocks.RED_TERRACOTTA).requiresTool());
    public static final Block BLACK_TERRACOTTA_SLAB = new AtbywSlabBlock(TERRACOTTA_SLAB_MAP, DyeColor.BLACK, FabricBlockSettings.copyOf(Blocks.BLACK_TERRACOTTA).requiresTool());
    public static final Block TERRACOTTA_BRICKS = new AtbywBlock(FabricBlockSettings.copyOf(Blocks.TERRACOTTA).requiresTool());
    public static final Block WHITE_TERRACOTTA_BRICKS = new AtbywBlock(TERRACOTTA_BRICKS_MAP, DyeColor.WHITE, FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).requiresTool());
    public static final Block ORANGE_TERRACOTTA_BRICKS = new AtbywBlock(TERRACOTTA_BRICKS_MAP, DyeColor.ORANGE, FabricBlockSettings.copyOf(Blocks.ORANGE_TERRACOTTA).requiresTool());
    public static final Block MAGENTA_TERRACOTTA_BRICKS = new AtbywBlock(TERRACOTTA_BRICKS_MAP, DyeColor.MAGENTA, FabricBlockSettings.copyOf(Blocks.MAGENTA_TERRACOTTA).requiresTool());
    public static final Block LIGHT_BLUE_TERRACOTTA_BRICKS = new AtbywBlock(TERRACOTTA_BRICKS_MAP, DyeColor.LIGHT_BLUE, FabricBlockSettings.copyOf(Blocks.LIGHT_BLUE_TERRACOTTA).requiresTool());
    public static final Block YELLOW_TERRACOTTA_BRICKS = new AtbywBlock(TERRACOTTA_BRICKS_MAP, DyeColor.YELLOW, FabricBlockSettings.copyOf(Blocks.YELLOW_TERRACOTTA).requiresTool());
    public static final Block LIME_TERRACOTTA_BRICKS = new AtbywBlock(TERRACOTTA_BRICKS_MAP, DyeColor.LIME, FabricBlockSettings.copyOf(Blocks.LIME_TERRACOTTA).requiresTool());
    public static final Block PINK_TERRACOTTA_BRICKS = new AtbywBlock(TERRACOTTA_BRICKS_MAP, DyeColor.PINK, FabricBlockSettings.copyOf(Blocks.PINK_TERRACOTTA).requiresTool());
    public static final Block GRAY_TERRACOTTA_BRICKS = new AtbywBlock(TERRACOTTA_BRICKS_MAP, DyeColor.GRAY, FabricBlockSettings.copyOf(Blocks.GRAY_TERRACOTTA).requiresTool());
    public static final Block LIGHT_GRAY_TERRACOTTA_BRICKS = new AtbywBlock(TERRACOTTA_BRICKS_MAP, DyeColor.LIGHT_GRAY, FabricBlockSettings.copyOf(Blocks.LIGHT_GRAY_TERRACOTTA).requiresTool());
    public static final Block CYAN_TERRACOTTA_BRICKS = new AtbywBlock(TERRACOTTA_BRICKS_MAP, DyeColor.CYAN, FabricBlockSettings.copyOf(Blocks.CYAN_TERRACOTTA).requiresTool());
    public static final Block PURPLE_TERRACOTTA_BRICKS = new AtbywBlock(TERRACOTTA_BRICKS_MAP, DyeColor.PURPLE, FabricBlockSettings.copyOf(Blocks.PURPLE_TERRACOTTA).requiresTool());
    public static final Block BLUE_TERRACOTTA_BRICKS = new AtbywBlock(TERRACOTTA_BRICKS_MAP, DyeColor.BLUE, FabricBlockSettings.copyOf(Blocks.BLUE_TERRACOTTA).requiresTool());
    public static final Block BROWN_TERRACOTTA_BRICKS = new AtbywBlock(TERRACOTTA_BRICKS_MAP, DyeColor.BROWN, FabricBlockSettings.copyOf(Blocks.BROWN_TERRACOTTA).requiresTool());
    public static final Block GREEN_TERRACOTTA_BRICKS = new AtbywBlock(TERRACOTTA_BRICKS_MAP, DyeColor.GREEN, FabricBlockSettings.copyOf(Blocks.GREEN_TERRACOTTA).requiresTool());
    public static final Block RED_TERRACOTTA_BRICKS = new AtbywBlock(TERRACOTTA_BRICKS_MAP, DyeColor.RED, FabricBlockSettings.copyOf(Blocks.RED_TERRACOTTA).requiresTool());
    public static final Block BLACK_TERRACOTTA_BRICKS = new AtbywBlock(TERRACOTTA_BRICKS_MAP, DyeColor.BLACK, FabricBlockSettings.copyOf(Blocks.BLACK_TERRACOTTA).requiresTool());
    public static final Block TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(Blocks.TERRACOTTA, FabricBlockSettings.copyOf(Blocks.TERRACOTTA).requiresTool());
    public static final Block WHITE_TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(TERRACOTTA_BRICKS_STAIRS_MAP, DyeColor.WHITE, Blocks.WHITE_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).requiresTool());
    public static final Block ORANGE_TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(TERRACOTTA_BRICKS_STAIRS_MAP, DyeColor.ORANGE, Blocks.ORANGE_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.ORANGE_TERRACOTTA).requiresTool());
    public static final Block MAGENTA_TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(TERRACOTTA_BRICKS_STAIRS_MAP, DyeColor.MAGENTA, Blocks.MAGENTA_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.MAGENTA_TERRACOTTA).requiresTool());
    public static final Block LIGHT_BLUE_TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(TERRACOTTA_BRICKS_STAIRS_MAP, DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.LIGHT_BLUE_TERRACOTTA).requiresTool());
    public static final Block YELLOW_TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(TERRACOTTA_BRICKS_STAIRS_MAP, DyeColor.YELLOW, Blocks.YELLOW_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.YELLOW_TERRACOTTA).requiresTool());
    public static final Block LIME_TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(TERRACOTTA_BRICKS_STAIRS_MAP, DyeColor.LIME, Blocks.LIME_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.LIME_TERRACOTTA).requiresTool());
    public static final Block PINK_TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(TERRACOTTA_BRICKS_STAIRS_MAP, DyeColor.PINK, Blocks.PINK_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.PINK_TERRACOTTA).requiresTool());
    public static final Block GRAY_TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(TERRACOTTA_BRICKS_STAIRS_MAP, DyeColor.GRAY, Blocks.GRAY_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.GRAY_TERRACOTTA).requiresTool());
    public static final Block LIGHT_GRAY_TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(TERRACOTTA_BRICKS_STAIRS_MAP, DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.LIGHT_GRAY_TERRACOTTA).requiresTool());
    public static final Block CYAN_TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(TERRACOTTA_BRICKS_STAIRS_MAP, DyeColor.CYAN, Blocks.CYAN_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.CYAN_TERRACOTTA).requiresTool());
    public static final Block PURPLE_TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(TERRACOTTA_BRICKS_STAIRS_MAP, DyeColor.PURPLE, Blocks.PURPLE_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.PURPLE_TERRACOTTA).requiresTool());
    public static final Block BLUE_TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(TERRACOTTA_BRICKS_STAIRS_MAP, DyeColor.BLUE, Blocks.BLUE_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.BLUE_TERRACOTTA).requiresTool());
    public static final Block BROWN_TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(TERRACOTTA_BRICKS_STAIRS_MAP, DyeColor.BROWN, Blocks.BROWN_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.BROWN_TERRACOTTA).requiresTool());
    public static final Block GREEN_TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(TERRACOTTA_BRICKS_STAIRS_MAP, DyeColor.GREEN, Blocks.GREEN_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.GREEN_TERRACOTTA).requiresTool());
    public static final Block RED_TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(TERRACOTTA_BRICKS_STAIRS_MAP, DyeColor.RED, Blocks.RED_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.RED_TERRACOTTA).requiresTool());
    public static final Block BLACK_TERRACOTTA_BRICKS_STAIRS = new AtbywStairsBlock(TERRACOTTA_BRICKS_STAIRS_MAP, DyeColor.BLACK, Blocks.BLACK_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.BLACK_TERRACOTTA).requiresTool());
    public static final Block TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(FabricBlockSettings.copyOf(Blocks.TERRACOTTA).requiresTool());
    public static final Block WHITE_TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(TERRACOTTA_BRICKS_SLAB_MAP, DyeColor.WHITE, FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).requiresTool());
    public static final Block ORANGE_TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(TERRACOTTA_BRICKS_SLAB_MAP, DyeColor.ORANGE, FabricBlockSettings.copyOf(Blocks.ORANGE_TERRACOTTA).requiresTool());
    public static final Block MAGENTA_TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(TERRACOTTA_BRICKS_SLAB_MAP, DyeColor.MAGENTA, FabricBlockSettings.copyOf(Blocks.MAGENTA_TERRACOTTA).requiresTool());
    public static final Block LIGHT_BLUE_TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(TERRACOTTA_BRICKS_SLAB_MAP, DyeColor.LIGHT_BLUE, FabricBlockSettings.copyOf(Blocks.LIGHT_BLUE_TERRACOTTA).requiresTool());
    public static final Block YELLOW_TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(TERRACOTTA_BRICKS_SLAB_MAP, DyeColor.YELLOW, FabricBlockSettings.copyOf(Blocks.YELLOW_TERRACOTTA).requiresTool());
    public static final Block LIME_TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(TERRACOTTA_BRICKS_SLAB_MAP, DyeColor.LIME, FabricBlockSettings.copyOf(Blocks.LIME_TERRACOTTA).requiresTool());
    public static final Block PINK_TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(TERRACOTTA_BRICKS_SLAB_MAP, DyeColor.PINK, FabricBlockSettings.copyOf(Blocks.PINK_TERRACOTTA).requiresTool());
    public static final Block GRAY_TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(TERRACOTTA_BRICKS_SLAB_MAP, DyeColor.GRAY, FabricBlockSettings.copyOf(Blocks.GRAY_TERRACOTTA).requiresTool());
    public static final Block LIGHT_GRAY_TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(TERRACOTTA_BRICKS_SLAB_MAP, DyeColor.LIGHT_GRAY, FabricBlockSettings.copyOf(Blocks.LIGHT_GRAY_TERRACOTTA).requiresTool());
    public static final Block CYAN_TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(TERRACOTTA_BRICKS_SLAB_MAP, DyeColor.CYAN, FabricBlockSettings.copyOf(Blocks.CYAN_TERRACOTTA).requiresTool());
    public static final Block PURPLE_TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(TERRACOTTA_BRICKS_SLAB_MAP, DyeColor.PURPLE, FabricBlockSettings.copyOf(Blocks.PURPLE_TERRACOTTA).requiresTool());
    public static final Block BLUE_TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(TERRACOTTA_BRICKS_SLAB_MAP, DyeColor.BLUE, FabricBlockSettings.copyOf(Blocks.BLUE_TERRACOTTA).requiresTool());
    public static final Block BROWN_TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(TERRACOTTA_BRICKS_SLAB_MAP, DyeColor.BROWN, FabricBlockSettings.copyOf(Blocks.BROWN_TERRACOTTA).requiresTool());
    public static final Block GREEN_TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(TERRACOTTA_BRICKS_SLAB_MAP, DyeColor.GREEN, FabricBlockSettings.copyOf(Blocks.GREEN_TERRACOTTA).requiresTool());
    public static final Block RED_TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(TERRACOTTA_BRICKS_SLAB_MAP, DyeColor.RED, FabricBlockSettings.copyOf(Blocks.RED_TERRACOTTA).requiresTool());
    public static final Block BLACK_TERRACOTTA_BRICKS_SLAB = new AtbywSlabBlock(TERRACOTTA_BRICKS_SLAB_MAP, DyeColor.BLACK, FabricBlockSettings.copyOf(Blocks.BLACK_TERRACOTTA).requiresTool());
    public static final Block WHITE_CONCRETE_STAIRS = new AtbywStairsBlock(CONCRETE_STAIRS_MAP, DyeColor.WHITE, Blocks.WHITE_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).requiresTool());
    public static final Block ORANGE_CONCRETE_STAIRS = new AtbywStairsBlock(CONCRETE_STAIRS_MAP, DyeColor.ORANGE, Blocks.ORANGE_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.ORANGE_TERRACOTTA).requiresTool());
    public static final Block MAGENTA_CONCRETE_STAIRS = new AtbywStairsBlock(CONCRETE_STAIRS_MAP, DyeColor.MAGENTA, Blocks.MAGENTA_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.MAGENTA_TERRACOTTA).requiresTool());
    public static final Block LIGHT_BLUE_CONCRETE_STAIRS = new AtbywStairsBlock(CONCRETE_STAIRS_MAP, DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.LIGHT_BLUE_TERRACOTTA).requiresTool());
    public static final Block YELLOW_CONCRETE_STAIRS = new AtbywStairsBlock(CONCRETE_STAIRS_MAP, DyeColor.YELLOW, Blocks.YELLOW_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.YELLOW_TERRACOTTA).requiresTool());
    public static final Block LIME_CONCRETE_STAIRS = new AtbywStairsBlock(CONCRETE_STAIRS_MAP, DyeColor.LIME, Blocks.LIME_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.LIME_TERRACOTTA).requiresTool());
    public static final Block PINK_CONCRETE_STAIRS = new AtbywStairsBlock(CONCRETE_STAIRS_MAP, DyeColor.PINK, Blocks.PINK_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.PINK_TERRACOTTA).requiresTool());
    public static final Block GRAY_CONCRETE_STAIRS = new AtbywStairsBlock(CONCRETE_STAIRS_MAP, DyeColor.GRAY, Blocks.GRAY_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.GRAY_TERRACOTTA).requiresTool());
    public static final Block LIGHT_GRAY_CONCRETE_STAIRS = new AtbywStairsBlock(CONCRETE_STAIRS_MAP, DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.LIGHT_GRAY_TERRACOTTA).requiresTool());
    public static final Block CYAN_CONCRETE_STAIRS = new AtbywStairsBlock(CONCRETE_STAIRS_MAP, DyeColor.CYAN, Blocks.CYAN_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.CYAN_TERRACOTTA).requiresTool());
    public static final Block PURPLE_CONCRETE_STAIRS = new AtbywStairsBlock(CONCRETE_STAIRS_MAP, DyeColor.PURPLE, Blocks.PURPLE_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.PURPLE_TERRACOTTA).requiresTool());
    public static final Block BLUE_CONCRETE_STAIRS = new AtbywStairsBlock(CONCRETE_STAIRS_MAP, DyeColor.BLUE, Blocks.BLUE_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.BLUE_TERRACOTTA).requiresTool());
    public static final Block BROWN_CONCRETE_STAIRS = new AtbywStairsBlock(CONCRETE_STAIRS_MAP, DyeColor.BROWN, Blocks.BROWN_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.BROWN_TERRACOTTA).requiresTool());
    public static final Block GREEN_CONCRETE_STAIRS = new AtbywStairsBlock(CONCRETE_STAIRS_MAP, DyeColor.GREEN, Blocks.GREEN_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.GREEN_TERRACOTTA).requiresTool());
    public static final Block RED_CONCRETE_STAIRS = new AtbywStairsBlock(CONCRETE_STAIRS_MAP, DyeColor.RED, Blocks.RED_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.RED_TERRACOTTA).requiresTool());
    public static final Block BLACK_CONCRETE_STAIRS = new AtbywStairsBlock(CONCRETE_STAIRS_MAP, DyeColor.BLACK, Blocks.BLACK_TERRACOTTA, FabricBlockSettings.copyOf(Blocks.BLACK_TERRACOTTA).requiresTool());
    public static final Block WHITE_CONCRETE_SLAB = new AtbywSlabBlock(CONCRETE_SLAB_MAP, DyeColor.WHITE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).requiresTool());
    public static final Block ORANGE_CONCRETE_SLAB = new AtbywSlabBlock(CONCRETE_SLAB_MAP, DyeColor.ORANGE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).requiresTool());
    public static final Block MAGENTA_CONCRETE_SLAB = new AtbywSlabBlock(CONCRETE_SLAB_MAP, DyeColor.MAGENTA, FabricBlockSettings.copyOf(Blocks.MAGENTA_CONCRETE).requiresTool());
    public static final Block LIGHT_BLUE_CONCRETE_SLAB = new AtbywSlabBlock(CONCRETE_SLAB_MAP, DyeColor.LIGHT_BLUE, FabricBlockSettings.copyOf(Blocks.LIGHT_BLUE_CONCRETE).requiresTool());
    public static final Block YELLOW_CONCRETE_SLAB = new AtbywSlabBlock(CONCRETE_SLAB_MAP, DyeColor.YELLOW, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).requiresTool());
    public static final Block LIME_CONCRETE_SLAB = new AtbywSlabBlock(CONCRETE_SLAB_MAP, DyeColor.LIME, FabricBlockSettings.copyOf(Blocks.LIME_CONCRETE).requiresTool());
    public static final Block PINK_CONCRETE_SLAB = new AtbywSlabBlock(CONCRETE_SLAB_MAP, DyeColor.PINK, FabricBlockSettings.copyOf(Blocks.PINK_CONCRETE).requiresTool());
    public static final Block GRAY_CONCRETE_SLAB = new AtbywSlabBlock(CONCRETE_SLAB_MAP, DyeColor.GRAY, FabricBlockSettings.copyOf(Blocks.GRAY_CONCRETE).requiresTool());
    public static final Block LIGHT_GRAY_CONCRETE_SLAB = new AtbywSlabBlock(CONCRETE_SLAB_MAP, DyeColor.LIGHT_GRAY, FabricBlockSettings.copyOf(Blocks.LIGHT_GRAY_CONCRETE).requiresTool());
    public static final Block CYAN_CONCRETE_SLAB = new AtbywSlabBlock(CONCRETE_SLAB_MAP, DyeColor.CYAN, FabricBlockSettings.copyOf(Blocks.CYAN_CONCRETE).requiresTool());
    public static final Block PURPLE_CONCRETE_SLAB = new AtbywSlabBlock(CONCRETE_SLAB_MAP, DyeColor.PURPLE, FabricBlockSettings.copyOf(Blocks.PURPLE_CONCRETE).requiresTool());
    public static final Block BLUE_CONCRETE_SLAB = new AtbywSlabBlock(CONCRETE_SLAB_MAP, DyeColor.BLUE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).requiresTool());
    public static final Block BROWN_CONCRETE_SLAB = new AtbywSlabBlock(CONCRETE_SLAB_MAP, DyeColor.BROWN, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).requiresTool());
    public static final Block GREEN_CONCRETE_SLAB = new AtbywSlabBlock(CONCRETE_SLAB_MAP, DyeColor.GREEN, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).requiresTool());
    public static final Block RED_CONCRETE_SLAB = new AtbywSlabBlock(CONCRETE_SLAB_MAP, DyeColor.RED, FabricBlockSettings.copyOf(Blocks.RED_CONCRETE).requiresTool());
    public static final Block BLACK_CONCRETE_SLAB = new AtbywSlabBlock(CONCRETE_SLAB_MAP, DyeColor.BLACK, FabricBlockSettings.copyOf(Blocks.BLACK_CONCRETE).requiresTool());
    public static final Block WHITE_CINDER_BLOCKS = new AtbywPillarBlock(CINDER_BRICKS_MAP, DyeColor.WHITE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).requiresTool());
    public static final Block ORANGE_CINDER_BLOCKS = new AtbywPillarBlock(CINDER_BRICKS_MAP, DyeColor.ORANGE, FabricBlockSettings.copyOf(Blocks.ORANGE_CONCRETE).requiresTool());
    public static final Block MAGENTA_CINDER_BLOCKS = new AtbywPillarBlock(CINDER_BRICKS_MAP, DyeColor.MAGENTA, FabricBlockSettings.copyOf(Blocks.MAGENTA_CONCRETE).requiresTool());
    public static final Block LIGHT_BLUE_CINDER_BLOCKS = new AtbywPillarBlock(CINDER_BRICKS_MAP, DyeColor.LIGHT_BLUE, FabricBlockSettings.copyOf(Blocks.LIGHT_BLUE_CONCRETE).requiresTool());
    public static final Block YELLOW_CINDER_BLOCKS = new AtbywPillarBlock(CINDER_BRICKS_MAP, DyeColor.YELLOW, FabricBlockSettings.copyOf(Blocks.YELLOW_CONCRETE).requiresTool());
    public static final Block LIME_CINDER_BLOCKS = new AtbywPillarBlock(CINDER_BRICKS_MAP, DyeColor.LIME, FabricBlockSettings.copyOf(Blocks.LIME_CONCRETE).requiresTool());
    public static final Block PINK_CINDER_BLOCKS = new AtbywPillarBlock(CINDER_BRICKS_MAP, DyeColor.PINK, FabricBlockSettings.copyOf(Blocks.PINK_CONCRETE).requiresTool());
    public static final Block GRAY_CINDER_BLOCKS = new AtbywPillarBlock(CINDER_BRICKS_MAP, DyeColor.GRAY, FabricBlockSettings.copyOf(Blocks.GRAY_CONCRETE).requiresTool());
    public static final Block LIGHT_GRAY_CINDER_BLOCKS = new AtbywPillarBlock(CINDER_BRICKS_MAP, DyeColor.LIGHT_GRAY, FabricBlockSettings.copyOf(Blocks.LIGHT_GRAY_CONCRETE).requiresTool());
    public static final Block CYAN_CINDER_BLOCKS = new AtbywPillarBlock(CINDER_BRICKS_MAP, DyeColor.CYAN, FabricBlockSettings.copyOf(Blocks.CYAN_CONCRETE).requiresTool());
    public static final Block PURPLE_CINDER_BLOCKS = new AtbywPillarBlock(CINDER_BRICKS_MAP, DyeColor.PURPLE, FabricBlockSettings.copyOf(Blocks.PURPLE_CONCRETE).requiresTool());
    public static final Block BLUE_CINDER_BLOCKS = new AtbywPillarBlock(CINDER_BRICKS_MAP, DyeColor.BLUE, FabricBlockSettings.copyOf(Blocks.BLUE_CONCRETE).requiresTool());
    public static final Block BROWN_CINDER_BLOCKS = new AtbywPillarBlock(CINDER_BRICKS_MAP, DyeColor.BROWN, FabricBlockSettings.copyOf(Blocks.BROWN_CONCRETE).requiresTool());
    public static final Block GREEN_CINDER_BLOCKS = new AtbywPillarBlock(CINDER_BRICKS_MAP, DyeColor.GREEN, FabricBlockSettings.copyOf(Blocks.GREEN_CONCRETE).requiresTool());
    public static final Block RED_CINDER_BLOCKS = new AtbywPillarBlock(CINDER_BRICKS_MAP, DyeColor.RED, FabricBlockSettings.copyOf(Blocks.RED_CONCRETE).requiresTool());
    public static final Block BLACK_CINDER_BLOCKS = new AtbywPillarBlock(CINDER_BRICKS_MAP, DyeColor.BLACK, FabricBlockSettings.copyOf(Blocks.BLACK_CONCRETE).requiresTool());
    public static final Block AMETHYST_BRICKS = new Block(FabricBlockSettings.copyOf(Blocks.AMETHYST_BLOCK).requiresTool());
    public static final Block AMETHYST_BRICKS_SLAB = new Block(FabricBlockSettings.copyOf(AMETHYST_BRICKS).requiresTool());
    public static final Block AMETHYST_BRICKS_STAIRS = new Block(FabricBlockSettings.copyOf(AMETHYST_BRICKS).requiresTool());
    public static final Block CHISELED_AMETHYST_BRICKS = new Block(FabricBlockSettings.copyOf(AMETHYST_BRICKS).requiresTool());
    public static final Block DRIPSTONE_BRICKS = new SurfaceFacingBlock(FabricBlockSettings.copyOf(Blocks.DRIPSTONE_BLOCK).requiresTool());
    public static final Block DRIPSTONE_BRICKS_SLAB = new SlabBlock(FabricBlockSettings.copyOf(DRIPSTONE_BRICKS).requiresTool());
    public static final Block DRIPSTONE_BRICKS_STAIRS = new AtbywStairsBlock(DRIPSTONE_BRICKS, FabricBlockSettings.copyOf(DRIPSTONE_BRICKS).requiresTool());
    public static final Block CHISELED_DRIPSTONE_BRICKS = new Block(FabricBlockSettings.copyOf(DRIPSTONE_BRICKS).requiresTool());

    private static FabricBlockSettings basaltSettings() {
        return FabricBlockSettings.of(Material.STONE, MapColor.BLACK).requiresTool().strength(1.25F, 4.2F).sounds(BlockSoundGroup.BASALT);
    }

    private static FabricBlockSettings logSettings(Block copiedBlock) {
        return FabricBlockSettings.of(Material.WOOD, copiedBlock.getDefaultMapColor()).strength(2.0F).sounds(copiedBlock.getSoundGroup(copiedBlock.getDefaultState()));
    }

    private static ShatteredGlassBlock createShatteredGlass(Block copiedBlock) {
        var settings = FabricBlockSettings.of(Material.GLASS).strength(0.3F).sounds(BlockSoundGroup.GLASS).nonOpaque().allowsSpawning(AtbywBlocks::never).solidBlock(AtbywBlocks::never).suffocates(AtbywBlocks::never).blockVision(AtbywBlocks::never);

        if (copiedBlock instanceof StainedGlassBlock stainedGlass) {
            return new ShatteredGlassBlock(SHATTERED_GLASS_MAP, stainedGlass.getColor(), stainedGlass, settings);
        } else {
            return new ShatteredGlassBlock(SHATTERED_GLASS_MAP, null, copiedBlock, settings);
        }
    }

    private static String getLogName(StringIdentifiable stringIdentifiable) {
        return ((WoodType) stringIdentifiable).isNetherWood() ? "stem" : "log";
    }

    public static void registerAll() {
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "granite_tiles", GRANITE_TILES);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "diorite_bricks", DIORITE_BRICKS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "andesite_bricks", ANDESITE_BRICKS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "granite_tiles_stairs", GRANITE_TILES_STAIRS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "diorite_bricks_stairs", DIORITE_BRICKS_STAIRS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "andesite_bricks_stairs", ANDESITE_BRICKS_STAIRS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "granite_tiles_slab", GRANITE_TILES_SLAB);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "diorite_bricks_slab", DIORITE_BRICKS_SLAB);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "andesite_bricks_slab", ANDESITE_BRICKS_SLAB);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "dripstone_bricks", DRIPSTONE_BRICKS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "chiseled_dripstone_bricks", CHISELED_DRIPSTONE_BRICKS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "dripstone_bricks_slab", DRIPSTONE_BRICKS_SLAB);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "dripstone_bricks_stairs", DRIPSTONE_BRICKS_STAIRS);
        registerBlock(BLOCKS_TAB, AXE_MINEABLE, "raw_cactus_planks", RAW_CACTUS_PLANKS);
        registerBlock(BLOCKS_TAB, AXE_MINEABLE, "cactus_planks", CACTUS_PLANKS);
        registerBlock(BLOCKS_TAB, AXE_MINEABLE, "cactus_slab", CACTUS_SLAB);
        registerBlock(BLOCKS_TAB, AXE_MINEABLE, "cactus_stairs", CACTUS_STAIRS);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "grass_block_stairs", GRASS_BLOCK_STAIRS);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "dirt_stairs", DIRT_STAIRS);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "coarse_dirt_stairs", COARSE_DIRT_STAIRS);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "podzol_stairs", PODZOL_STAIRS);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "rooted_dirt_stairs", ROOTED_DIRT_STAIRS);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "mycelium_stairs", MYCELIUM_STAIRS);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "grass_path_stairs", GRASS_PATH_STAIRS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "crimson_nylium_stairs", CRIMSON_NYLIUM_STAIRS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "warped_nylium_stairs", WARPED_NYLIUM_STAIRS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "netherrack_stairs", NETHERRACK_STAIRS);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "sand_stairs", SAND_STAIRS);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "red_sand_stairs", RED_SAND_STAIRS);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "gravel_stairs", GRAVEL_STAIRS);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "grass_block_slab", GRASS_BLOCK_SLAB);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "dirt_slab", DIRT_SLAB);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "coarse_dirt_slab", COARSE_DIRT_SLAB);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "podzol_slab", PODZOL_SLAB);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "rooted_dirt_slab", ROOTED_DIRT_SLAB);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "mycelium_slab", MYCELIUM_SLAB);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "grass_path_slab", GRASS_PATH_SLAB);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "crimson_nylium_slab", CRIMSON_NYLIUM_SLAB);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "warped_nylium_slab", WARPED_NYLIUM_SLAB);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "netherrack_slab", NETHERRACK_SLAB);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "sand_slab", SAND_SLAB);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "red_sand_slab", RED_SAND_SLAB);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "gravel_slab", GRAVEL_SLAB);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "amethyst_bricks", AMETHYST_BRICKS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "chiseled_amethyst_bricks", CHISELED_AMETHYST_BRICKS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "amethyst_bricks_slab", AMETHYST_BRICKS_SLAB);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "amethyst_bricks_stairs", AMETHYST_BRICKS_STAIRS);
        registerColoredBlocks(BLOCKS_TAB, AXE_MINEABLE, (str) -> getLogName(str) + "_stairs", CUT_LOG_STAIRS_MAP);
        registerColoredBlocks(BLOCKS_TAB, AXE_MINEABLE, "cut", (str) -> getLogName(str) + "_stairs", LOG_STAIRS_MAP);
        registerColoredBlocks(BLOCKS_TAB, AXE_MINEABLE, "stripped", (str) -> getLogName(str) + "_stairs", STRIPPED_LOG_STAIRS_MAP);
        registerColoredBlocks(BLOCKS_TAB, AXE_MINEABLE, "stripped_cut", (str) -> getLogName(str) + "_stairs", STRIPPED_CUT_LOG_STAIRS_MAP);
        registerColoredBlocks(BLOCKS_TAB, AXE_MINEABLE, (str) -> getLogName(str) + "_slab", LOG_SLAB_MAP);
        registerColoredBlocks(BLOCKS_TAB, AXE_MINEABLE, "stripped", (str) -> getLogName(str) + "_slab", STRIPPED_LOG_SLAB_MAP);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "shattered_glass", SHATTERED_GLASS);
        registerBlock(BLOCKS_TAB, AXE_MINEABLE, "soul_jack_o_lantern", SOUL_JACK_O_LANTERN);
        registerColoredBlocks(BLOCKS_TAB, AXE_MINEABLE, "bookshelf", BOOKSHELF_MAP);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "purpur_tiles", PURPUR_TILES);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "chiseled_purpur_block", CHISELED_PURPUR_BLOCK);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "cut_purpur_block", CUT_PURPUR_BLOCK);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "smooth_purpur_block", SMOOTH_PURPUR_BLOCK);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "purpur_tiles_stairs", PURPUR_TILES_STAIRS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "cut_purpur_stairs", CUT_PURPUR_STAIRS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "smooth_purpur_stairs", SMOOTH_PURPUR_STAIRS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "purpur_tiles_slab", PURPUR_TILES_SLAB);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "cut_purpur_slab", CUT_PURPUR_SLAB);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "smooth_purpur_slab", SMOOTH_PURPUR_SLAB);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "compacted_snow_block", COMPACTED_SNOW_BLOCK);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "compacted_snow_bricks", COMPACTED_SNOW_BRICKS);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "chiseled_compacted_snow_bricks", CHISELED_COMPACTED_SNOW_BRICKS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "packed_ice_bricks", PACKED_ICE_BRICKS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "chiseled_packed_ice_bricks", CHISELED_PACKED_ICE_BRICKS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "blue_ice_bricks", BLUE_ICE_BRICKS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "chiseled_blue_ice_bricks", CHISELED_BLUE_ICE_BRICKS);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "compacted_snow_block_stairs", COMPACTED_SNOW_BLOCK_STAIRS);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "compacted_snow_bricks_stairs", COMPACTED_SNOW_BRICKS_STAIRS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "packed_ice_stairs", PACKED_ICE_STAIRS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "blue_ice_stairs", BLUE_ICE_STAIRS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "packed_ice_bricks_stairs", PACKED_ICE_BRICKS_STAIRS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "blue_ice_bricks_stairs", BLUE_ICE_BRICKS_STAIRS);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "compacted_snow_block_slab", COMPACTED_SNOW_BLOCK_SLAB);
        registerBlock(BLOCKS_TAB, SHOVEL_MINEABLE, "compacted_snow_bricks_slab", COMPACTED_SNOW_BRICKS_SLAB);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "packed_ice_slab", PACKED_ICE_SLAB);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "blue_ice_slab", BLUE_ICE_SLAB);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "packed_ice_bricks_slab", PACKED_ICE_BRICKS_SLAB);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "blue_ice_bricks_slab", BLUE_ICE_BRICKS_SLAB);
        registerColoredBlocks(BLOCKS_TAB, PICKAXE_MINEABLE, "stained_shattered_glass", SHATTERED_GLASS_MAP);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "basalt_bricks", BASALT_BRICKS);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "basalt_pillar", BASALT_PILLAR);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "terracotta_stairs", TERRACOTTA_STAIRS);
        registerColoredBlocks(BLOCKS_TAB, PICKAXE_MINEABLE, "terracotta_stairs", TERRACOTTA_STAIRS_MAP);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "terracotta_slab", TERRACOTTA_SLAB);
        registerColoredBlocks(BLOCKS_TAB, PICKAXE_MINEABLE, "terracotta_slab", TERRACOTTA_SLAB_MAP);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "terracotta_bricks", TERRACOTTA_BRICKS);
        registerColoredBlocks(BLOCKS_TAB, PICKAXE_MINEABLE, "terracotta_bricks", TERRACOTTA_BRICKS_MAP);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "terracotta_bricks_stairs", TERRACOTTA_BRICKS_STAIRS);
        registerColoredBlocks(BLOCKS_TAB, PICKAXE_MINEABLE, "terracotta_bricks_stairs", TERRACOTTA_BRICKS_STAIRS_MAP);
        registerBlock(BLOCKS_TAB, PICKAXE_MINEABLE, "terracotta_bricks_slab", TERRACOTTA_BRICKS_SLAB);
        registerColoredBlocks(BLOCKS_TAB, PICKAXE_MINEABLE, "terracotta_bricks_slab", TERRACOTTA_BRICKS_SLAB_MAP);
        registerColoredBlocks(BLOCKS_TAB, PICKAXE_MINEABLE, "concrete_stairs", CONCRETE_STAIRS_MAP);
        registerColoredBlocks(BLOCKS_TAB, PICKAXE_MINEABLE, "concrete_slab", CONCRETE_SLAB_MAP);
        registerColoredBlocks(BLOCKS_TAB, PICKAXE_MINEABLE, "cinder_bricks", CINDER_BRICKS_MAP);
    }
}
